### ISSUE TITLE
OSX El Capitan Setup Failure

### ISSUE THREAD

**Issue by T3LC0** [R3C0Nx00/haxxor-framework#3]
Due to the new System Integrity Protection OS X El Capitan will not allow installation in /usr it needs installation in /usr/local/

**Comment by R3C0Nx00** [comment]
I will write a Mac specific setup script so it moves haxxor.py to /usr/local instead of /usr/bin

**Comment by R3C0Nx00** [comment]
Wait you're talking about the /usr/haxxor directory right?

**Comment by R3C0Nx00** [comment]
Could you post the error output you are getting?

**Comment by R3C0Nx00** [comment]
Error will be fixed.
